def error(msg: object) -> None: ...
def info(msg: object) -> None: ...
def warning(msg: object) -> None: ...
def success(msg: object) -> None: ...
def write(*args: object, **kwargs: object) -> None: ...

class DeltaGenerator: ...
